### ISSUE TITLE
support `.js` extension for imports in `.ts` files

### ISSUE THREAD

**Issue by dominikg** [lukeed/tsm#1] opened 2021-10-05 09:19 UTC
It is supported in ts-node/esm and according to typescript that's the recommended way to import
https://twitter.com/orta/status/1444958295865937920

foo.ts
```ts
import bar from './bar.js'  // bar.js does not exist on disk, it is the transpilation result of bar.ts
```

Right now this fails with ENOENT, here's how it looks like in uvu's typescript.module example when you use math.ts and utils.ts instead of .js

```
devDependencies:
+ loadr 0.1.1
+ tsm 2.0.0
+ uvu 0.5.1
dominikg@mb14:~/develop/uvu/examples/typescript.module$ pnpm test

> @ test /home/dominikg/develop/uvu/examples/typescript.module
> tsm node_modules/uvu/bin.js tests

(node:8503) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: ENOENT: no such file or directory, open '/home/dominikg/develop/uvu/examples/typescript.module/src/math.js'
```

**Comment by lukeed** [comment] 2021-10-05 10:57
Waiting on the next version of esbuild which might handle this automatically: https://github.com/evanw/esbuild/issues/1505#issuecomment-934070846

Also, TS 4.5 is still in beta so this isn't officially doable yet

**Comment by lukeed** [comment] 2021-10-05 11:42
Also, could you just drop the extension in this case?

```js
import * as math from '../src/math';
// resolves to math.ts cuz it exists
```

That uvu example only includes the ".js" extension inside the import to match the reproduction it was closing. The other "typescript" example doesn't include extensions in the imports because TS has never needed it when importing another TS file.

**Comment by dominikg** [comment] 2021-10-05 12:09
My understanding of authoring typescript esm is that you should always use `import from 'foo.js'` in .ts files , not `import from 'foo.ts'` or `import from 'foo'`. - Please correct me if i'm wrong here.
Dropping the extension works, but if using .js is the official recommendation, tsm should support it.

re 4.5. I think that only adds support for mts/cts, 4.4 already works with `"type": "module"` in package.json and .ts files importing .js extension

**Comment by lukeed** [comment] 2021-10-05 12:34
I've always left off extensions, but I also always only use TS alongside a bundler of some kind, so it doesn't matter. Going extension-less & relying on `tsc` output alone to produce JS files (with ESM flavor) would put you in a bad spot since the output also wouldn't include an extension, making the ESM runtime (node or browser) bail.

But you're right, it should match. 

Playing with it now – fairly easy on the ESM side. Unblocking `--require tsm` might be a little trickier.

**Comment by lukeed** [comment] 2021-10-05 16:04
Resolved :) Thanks for opening this up

**Closed** 2021-10-05 16:05 UTC

**Comment by karlhorky** [comment] 2022-03-25 16:16
Opened a PR instead: https://github.com/lukeed/tsm/pull/33

**Comment by karlhorky** [comment] 2022-11-28 11:05
Nice, `tsm@2.3.0` (PR #43) is working, thanks! 🙌
