### ISSUE TITLE
Deprecated hooks

### ISSUE THREAD

**Issue by kran6a** [lukeed/tsm#34] opened 2022-06-25 18:30 UTC
On the lastest node.js version the following error is thrown:

`DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource`

Meaning some features will not work properly unless those hooks are moved into the new `load` hook.

**Comment by TrySound** [comment] 2022-06-25 21:35
Not an error. Just a warning. This is because older versions are still supported along with new hooks. Shouldn't affect anything.

**Comment by lukeed** [comment] 2022-06-26 16:48
Closing as duplicate of #12

**Closed by lukeed** 2022-06-26 16:48 UTC
